apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ismajabbb/gitops-config.git
    targetRevision: main
    path: gitops/apps/myapp/overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

